# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

appearance:
  # mode: dark
  theme_day: rose
  theme_night: dark
  font: "my_custom_fonts"
  font_size: S

# SEO

marketing:
  seo:
    site_type: Person
    local_business_type: ""
    org_name: ""
    description: ""
    twitter: "lehan_W"
  analytics:
    google_analytics: ""
    baidu_tongji: ""
    google_tag_manager: ""
    microsoft_clarity: ""
  verification:
    google: ""
    baidu: ""

# Site header

header:
  navbar:
    enable: true
    align: l
    show_logo: true
    show_language: false
    show_day_night: true
    show_search: true
    highlight_active_link: true

# Site footer

footer:
  copyright:
    notice: ""
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization

locale:
  date_format: "Jan 2, 2006"
  time_format: "3:04 PM"
  address_format: en-us

# Site features

features:
  syntax_highlighter:
    enable: true
    extra_languages:
      - r
      - latex
  math:
    enable: true
  privacy_pack:
    enable: false
  repository:
    url: "https://github.com/luxuriant0116/luxuriant0116.github.io"
    content_dir: content
    branch: master
  avatar:
    gravatar: true
    shape: circle
  comment:
    provider: ""
    disqus:
      shortname: ""
      show_count: true
    commento:
      url: ""
    giscus:
      repo: ""
      repo_id: ""
      category: ""
      category_id: ""
  search:
    provider: wowchemy
    algolia:
      app_id: ""
      api_key: ""
      index_name: ""
      show_logo: false
  map:
    provider: "mapnik"
    api_key: ""
    zoom: 15

# Extensions

extensions:
  cms:
    branch: main
    local_backend: false
  academicons:
    enable: true

# Security

security:
  # Allow frame for embedding speaker notes in slides
  allow_frame: true
  # # Breaking changes in Hugo 0.91.0 · HugoBlox/hugo-blox-builder · Discussion #2559 https://github.com/HugoBlox/hugo-blox-builder/discussions/2559
  # funcs:
  #   getenv:
  #     - ^HUGO_
  #     - ^WC_
